const base_url = 'https://nuska.kg/api/v1/';

const API_URLS = {
  base_url: base_url,
  library: base_url + 'library/book_list/',
  authors: base_url + 'library/author_list/',
  bestselling: base_url + 'library/bestselling_books/',
  oneBook: base_url + 'library/book_detail/',
  register: base_url + 'authentication/register/',
  authorization: base_url + 'authentication/login/',
  genres: base_url + 'library/jenre_list/',
  newbooks: base_url + 'library/newbooks/',
  user: base_url + 'account/users/me/',
  addFavoriteBook: base_url + 'library/addfavoritebook/',
  deletefavoritebook: base_url + 'library/deletefavoritebook/',
  favoriteBookList: base_url + 'library/favoritebook-list/',
  commentList: base_url + 'library/comment_list_create/',
  createComment: base_url + 'library/comment_list_create/',
  refresh_token: base_url + 'authentication/token/refresh/',
  reset_password: base_url + 'authentication/users/reset/password/',
  code_confirm: base_url + 'authentication/users/reset/code/confirm/',
  change_password: base_url + 'authentication/users/reset/password/confirm/',
  recommendedBooks: base_url + 'library/recommended/books',
  author_books: base_url + 'account/mybooks/',
  delete_account: base_url + 'account/delete/account/',
  patch_username: base_url + 'account/user/update/',
  purchased_books: base_url + 'orders/purchased/book/',
  public_offers: base_url + 'orders/public_offer',
};
export default API_URLS;
